services:
  auth-service:
    image: auth-service:1.0
    container_name: auth-service
    restart: always
    environment:
      DATABASE_URL: "postgres://auth_service:auth_service@2026@auth-service-db:5432/auth_db"
      PORT: "8001"
      MASTER_KEY: "admin-key@2026"
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 30s
    depends_on:
      auth-service-db:
        condition: service_healthy
    networks:
      - fase2
      
  auth-service-db:
    image: custom-postgres:17
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_USER: auth_service
      POSTGRES_PASSWORD: auth_service@2026
      POSTGRES_DB: auth_db
    ports:
      - "5439:5432"
    volumes:
      - /home/vinicius.mendes/Docker/volumes/auth_db:/var/lib/postgresql/data
      - ../auth-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_service -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fase2

  flag-service:
    image: flag-service:1.0
    container_name: flag-service
    restart: always
    environment:
      DATABASE_URL: "postgres://flag_service:flag_service2026@flag-service-db:5432/flags_db"
      PORT: "8002"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 45s
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - fase2

  flag-service-db:
    image: custom-postgres:17
    container_name: flag-service-db
    restart: always
    environment:
      POSTGRES_USER: flag_service
      POSTGRES_PASSWORD: flag_service2026
      POSTGRES_DB: flags_db
    ports:
      - "5440:5432"
    volumes:
      - /home/vinicius.mendes/Docker/volumes/flags_db:/var/lib/postgresql/data
      - ../flag-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flag_service -d flags_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fase2

  targeting-service:
    image: targeting-service:1.0
    container_name: targeting-service
    restart: always
    environment:
      DATABASE_URL: "postgres://targeting_service:targeting_service2026@targeting-service-db:5432/targeting_db"
      PORT: "8003"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 45s
    depends_on:
      auth-service:
        condition: service_healthy
    networks:
      - fase2

  targeting-service-db:
    image: custom-postgres:17
    container_name: targeting-service-db
    restart: always
    environment:
      POSTGRES_USER: targeting_service
      POSTGRES_PASSWORD: targeting_service2026
      POSTGRES_DB: targeting_db
    ports:
      - "5441:5432"
    volumes:
      - /home/vinicius.mendes/Docker/volumes/targeting_db:/var/lib/postgresql/data
      - ../targeting-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U targeting_service -d targeting_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - fase2

  evaluation-service:
    image: evaluation-service:1.0
    container_name: evaluation-service
    restart: always
    environment:
      PORT: "8004"
      REDIS_URL: "redis://redis:6379"
      FLAG_SERVICE_URL: "http://flag-service:8002"
      TARGETING_SERVICE_URL: "http://targeting-service:8003"
      SERVICE_API_KEY: "tm_key_59f8679dad31f9f0cc03ee6f12d6214b07224d37abca178b2529681c7b893349"
      AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/123456789012/sua-fila"
      AWS_REGION: "us-east-1" 
    ports:
      - "8004:8004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 45s
    depends_on:
      auth-service:
        condition: service_healthy
      flag-service:
        condition: service_healthy
      targeting-service:
        condition: service_healthy
    networks:
      - fase2

  redis:
    image: custom-redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /home/vinicius.mendes/Docker/volumes/redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - fase2

networks:
  fase2:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1