apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-keda-secrets
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVJEWlpJVFlGUzJXR000TEI=
  AWS_SECRET_ACCESS_KEY: WHNQVGlSQVp3aXU1SWlJU2JqTUNOVWJ0RTBlaEE3cDQ3Y3Y4Vk9vNA==
  AWS_SESSION_TOKEN: SVFvSmIzSnBaMmx1WDJWakVKTC8vLy8vLy8vLy93RWFDWFZ6TFhkbGMzUXRNaUpHTUVRQ0lBREpNeVB5Z1h0aUI4WmFXdmV0K1lnOG5zSHBTeTZldldoNHE4TEU0M3gwQWlCNTlrWjFmdlRFRkJQN1JCSXp3MTJlaUJEZHdtWi96T0U1SnFndWJ3a2dYQ3E0QWdoYkVBQWFEREEzTmpnNU1qWTBNamd5TnlJTWZhMm9oTGtqSFRuN29rd1dLcFVDMEhLT0VXYldzVDcxZFZJNHl3UHpjYWt5LzRKOFdyd25ZbElMS2VKQmF4NzdyQm8xUEkwOEFvQTdoVjlwWmxjNlFTT3FXa1laOUQzQTFnNkdGV0JnVXVycmhiOUw5ak1lODJBdWt2ZXpXUXBIZldjOVZudWRQTWFVdzBQRS9oSzdKOU0rL1ZxRFh3VXRWME80T2orVm5hekhaZnhURHdvMEVzVjJvS0psdVpQUEFrU2Evd1o5MkRWcE1hcVgxM1VPQStSTmZoWGJ3d1ZqY0lmY0IzMnRnellOV3JES1QwVGFYZGR2MnJFUUZoWUJ6YTVYMExTNkxIY1gyb29XT0dUaDJGMVdOSFdkQlZ1WVFVclp2Sk9yWDZzTlMrMUJ0Nlk3T0h3OUJoZVc5RVJtbEUrSDJ0eW50U3dLRzYzT01QOG5IM2kvYnpZMGxVU1dBTVliTUQvelpaUGlKVjVxMHhwNG13bWFQTFhBOWY5R2t2RnhEakNqMmEvU0JqcWVBZHdZSlhXaS9DZFo5WVB1Y082T21wbEtpV0NJWEFGQlhMNUxUT2Nkc3JlT2NBWmhmSjF5SW56NFp3YzZxb1pRV1RPbVlxVUNIMXRaaUpiNTNMdS9nU1lIKzRWaWxkSkRNVFZFaVl2alc5UmkwZncrd3dqai9LK2Fka05TQVpQWHh5MU1KeUNEZjlVK3ZBeEgxaHVQb1hXSnoxUVpLbU50ZTVjTnZiQzFWZjJmd1o3NkZEMXowdEpxUGJQYitDTlc0L1ZVRE96bXRBSHJmOUNsMW5lRA==
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: analytics-service-keda-trigger-auth-aws-credentials
  namespace: application
spec:
  secretTargetRef:
  - parameter: awsAccessKeyID
    name: analytics-service-keda-secrets
    key: AWS_ACCESS_KEY_ID
  - parameter: awsSecretAccessKey
    name: analytics-service-keda-secrets
    key: AWS_SECRET_ACCESS_KEY
  - parameter: awsSessionToken
    name: analytics-service-keda-secrets
    key: AWS_SESSION_TOKEN
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-service-keda-sqs-scale
  namespace: application
spec:
  scaleTargetRef:
    kind: Deployment
    name: analytics-service
  minReplicaCount: 0
  maxReplicaCount: 5
  cooldownPeriod:  30
  pollingInterval: 10
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: analytics-service-keda-trigger-auth-aws-credentials
    metadata:
      queueURL: queue-toggle-master
      queueLength: "5"
      awsRegion: "us-east-1"