apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-aws-secret
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVJEWlpJVFlGV1pXUFpBRFQ=
  AWS_SECRET_ACCESS_KEY: K2hJKzRHZEdzakxzUEZtQWJvTENLR2hPMkN5SlhCSGZQdVNHS2hMag==