apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-aws-secret
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVJEWlpJVFlGN0ZDUUNaVUc=
  AWS_SECRET_ACCESS_KEY: YjQyTWtmMEVNM0tjMGN6dW04T2k3MlpjVVc4b2RpV242THRXenJoQQ==