apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-aws-secret
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVJEWlpJVFlGUzJXR000TEI=
  AWS_SECRET_ACCESS_KEY: WHNQVGlSQVp3aXU1SWlJU2JqTUNOVWJ0RTBlaEE3cDQ3Y3Y4Vk9vNA==