FROM postgres:17-alpine

# Set default environment variables (Override these at runtime)
#ENV POSTGRES_USER=username
#ENV POSTGRES_PASSWORD=password
#ENV POSTGRES_DB=database

# Expose the default PostgreSQL port
EXPOSE 5432