apiVersion: v1
kind: Service
metadata:
  name: auth-service-backend
  namespace: ingress
spec:
  type: ExternalName
  externalName: auth-service-svc.application.svc.cluster.local
  ports:
  - port: 8001
    targetPort: 8001