apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-service-db-pvc
  namespace: fiap
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi