apiVersion: v1
kind: Service
metadata:
  name: auth-service-db-svc
  namespace: fiap
spec:
  type: NodePort
  selector:
    app: auth-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30439