apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticmq
  namespace: elasticmq
  labels:
    app: elasticmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticmq
  template:
    metadata:
      labels:
        app: elasticmq
    spec:
      #securityContext:
      #  runAsUser: 999
      #  runAsGroup: 1000
      #  fsGroup: 1000
      containers:
      - name: elasticmq
        image: custom-elasticmq:1.7.1
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
        #  readOnlyRootFilesystem: false
        resources:
          limits:
            cpu: "200m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        startupProbe:
          exec:
            command:
              - wget
              - --spider
              - -q
              - http://localhost:9324/health
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 9
        livenessProbe:
          exec:
            command:
              - wget
              - --spider
              - -q
              - http://localhost:9324/health
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
              - wget
              - --spider
              - -q
              - http://localhost:9324/health
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        ports:
        - name: sqs-port
          containerPort: 9324
          protocol: TCP
        - name: http-port
          containerPort: 9325
          protocol: TCP
        volumeMounts:
        - name: elasticmq-data
          mountPath: /opt/elasticmq.conf
          subPath: elasticmq.conf
      volumes:
      - name: elasticmq-data
        persistentVolumeClaim:
          claimName: elasticmq-pvc
      restartPolicy: Always
