apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticmq-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: elasticmq-pvc
    namespace: elasticmq
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/volumes/elasticmq"
    type: DirectoryOrCreate