apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticmq-pvc
  namespace: elasticmq
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi