apiVersion: v1
kind: Service
metadata:
  name: elasticmq-svc
  namespace: elasticmq
spec:
  type: ClusterIP
  selector:
    app: elasticmq
  ports:
    - protocol: TCP
      name: sqs-port
      port: 9324
      targetPort: 9324
    - protocol: TCP
      name: http-port
      port: 9325
      targetPort: 9325