apiVersion: v1
kind: Service
metadata:
  name: dynamodb-svc
  namespace: dynamodb
spec:
  type: ClusterIP
  selector:
    app: dynamodb
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000