apiVersion: v1
kind: Secret
metadata:
  name: auth-service-database-url-secret
  namespace: application
type: Opaque
stringData:
  DATABASE_URL: postgres://auth_service:auth_service@2026@auth-service-db-svc.postgres.svc.cluster.local:5432/auth_db
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-master-key-secret
  namespace: application
type: Opaque
data:
  MASTER_KEY: YWRtaW4ta2V5QDIwMjYK