apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-pvc
  namespace: dynamodb
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi