apiVersion: v1
kind: PersistentVolume
metadata:
  name: targeting-service-db-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: targeting-service-db-pvc
    namespace: postgres
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/volumes/targeting_db"