apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-api-key-secret
  namespace: application
type: Opaque
data:
  SERVICE_API_KEY: dG1fa2V5XzY3OTY3ZWRhMjQzZDhkMzYzNTFlNGVhZmU2YzJlZTM0ZWExNDM2NWZhMzAzNjc1MzE1ODE1NjkxNDU0NjA5MjQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-aws-secret
  namespace: application
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QVNJQVJEWlpJVFlGN0ZDUUNaVUc=
  AWS_SECRET_ACCESS_KEY: YjQyTWtmMEVNM0tjMGN6dW04T2k3MlpjVVc4b2RpV242THRXenJoQQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: evaluation-service-redis-secret
  namespace: application
type: Opaque
data:
  REDIS_URL: cmVkaXM6Ly90b2dnbGUtbWFzdGVyOnRvZ2dsZS1tYXN0ZXIxMjNAbWFzdGVyLnJlZGlzLWRldi5jaGxwaWQudXNlMS5jYWNoZS5hbWF6b25hd3MuY29tOjYzNzk=